[package]
name = "examples"
version = "0.1.0"
edition = "2024"

[dependencies.secure-types]
path = ".."

[dependencies.zeroize]
version = "1.8.1"


[[bin]]
name = "dump-test"
path = "src/dump_test.rs"